Repository Challenge-Hanbang-E/Hanbang-E, pull requests merged in 2023-01, with the labels that each got.

#2 ✨ Feat : 프로젝트 초기 세팅
  gradlew.bat
  src/main/java/com/hanbang/e/common/dto/ResponseDto.java
  src/main/java/com/hanbang/e/common/exception/GlobalExceptionHandler.java
  src/main/java/com/hanbang/e/member/entity/Member.java
  src/main/java/com/hanbang/e/member/repository/MemberRepository.java
  src/main/java/com/hanbang/e/order/entity/Order.java
  src/main/java/com/hanbang/e/order/entity/OrderedProduct.java
  src/main/java/com/hanbang/e/order/repository/OrderRepository.java
  src/main/java/com/hanbang/e/order/repository/OrderedRepository.java
  src/main/java/com/hanbang/e/product/entity/Brand.java
  src/main/java/com/hanbang/e/product/entity/Product.java
  src/main/java/com/hanbang/e/product/repository/BrandRepository.java
  src/main/java/com/hanbang/e/product/repository/ProductRepository.java
  src/main/resources/application.properties
Labels: good first issue, feature

#7 ✨ Feat: 상품 검색 API, 조회 API 추가
  build.gradle
  src/main/java/com/hanbang/e/product/controller/ProductController.java
  src/main/java/com/hanbang/e/product/dto/ProductDetailResp.java
  src/main/java/com/hanbang/e/product/dto/ProductListResp.java
  src/main/java/com/hanbang/e/product/dto/ProductSimpleResp.java
  src/main/java/com/hanbang/e/product/entity/Brand.java
  src/main/java/com/hanbang/e/product/entity/Product.java
  src/main/java/com/hanbang/e/product/repository/ProductRepository.java
  src/main/java/com/hanbang/e/product/service/ProductService.java
  src/main/resources/db/productDomainTableInit.sql
  src/test/java/com/hanbang/e/product/controller/ProductControllerTest.java
  src/test/java/com/hanbang/e/product/repository/ProductRepositoryTest.java
  src/test/java/com/hanbang/e/product/service/ProductServiceTest.java
Labels: feature

#13 🔥 Remove: 제품 브랜드 관련 정보 제거에 따른 코드 수정
  src/main/java/com/hanbang/e/product/dto/ProductDetailResp.java
  src/main/java/com/hanbang/e/product/dto/ProductSimpleResp.java
  src/main/java/com/hanbang/e/product/entity/Brand.java
  src/main/java/com/hanbang/e/product/entity/Product.java
  src/main/java/com/hanbang/e/product/repository/BrandRepository.java
  src/test/java/com/hanbang/e/product/controller/ProductControllerTest.java
  src/test/java/com/hanbang/e/product/repository/ProductRepositoryTest.java
  src/test/java/com/hanbang/e/product/service/ProductServiceTest.java
Labels: enhancement

#8 ✨ Feat : 회원가입 API 추가
  src/main/java/com/hanbang/e/member/controller/MemberController.java
  src/main/java/com/hanbang/e/member/dto/MemberCreateReq.java
  src/main/java/com/hanbang/e/member/dto/MemberResp.java
  src/main/java/com/hanbang/e/member/entity/Member.java
  src/main/java/com/hanbang/e/member/repository/MemberRepository.java
  src/main/java/com/hanbang/e/member/service/MemberService.java
  src/test/java/com/hanbang/e/member/controller/MemberControllerTest.java
  src/test/java/com/hanbang/e/member/repository/MemberRepositoryTest.java
  src/test/java/com/hanbang/e/member/service/MemberServiceTest.java
Labels: feature

#19 🔨️ Refactor : 코드 충돌 해결과정에서 일어난 오류 해결
  src/test/java/com/hanbang/e/order/service/OrderServiceTest.java
Labels: refactor

#21 ✨ Feat, 👷 Build : 프론트와의 연동 환경 작업
  build.gradle
  src/main/java/com/hanbang/e/common/config/WebConfig.java
  src/main/resources/application.properties
  src/test/resources/application-test.properties
Labels: feature

#23 ✨ Feat : 주문 삭제 기능 요구사항 변경에 따른 기능 추가
  src/main/java/com/hanbang/e/common/config/WebConfig.java
  src/main/java/com/hanbang/e/order/service/OrderService.java
  src/main/java/com/hanbang/e/product/entity/Product.java
Labels: enhancement

#16 ✨ Feat : 로그인 API 추가
  .gitignore
  src/main/java/com/hanbang/e/common/dto/ResponseDto.java
  src/main/java/com/hanbang/e/common/jwt/JwtUtil.java
  src/main/java/com/hanbang/e/member/controller/MemberController.java
  src/main/java/com/hanbang/e/member/dto/MemberLoginReq.java
  src/main/java/com/hanbang/e/member/service/MemberService.java
  src/main/resources/application.properties
  src/test/java/com/hanbang/e/member/controller/MemberControllerTest.java
  src/test/java/com/hanbang/e/member/repository/MemberRepositoryTest.java
  src/test/java/com/hanbang/e/member/service/MemberServiceTest.java
  src/test/java/com/hanbang/e/member/util/JwtUtilTest.java
Labels: feature

#26 🐛 Fix : 회원가입 API 통신 오류
  src/main/java/com/hanbang/e/member/dto/MemberCreateReq.java
  src/main/java/com/hanbang/e/member/dto/MemberLoginReq.java
Labels: bugfix

#27 📝 Chore : build.gradle 의존성 주입
  build.gradle
Labels: refactor

#29 📝 Chore : 테스트 시 application.properties 변경하지 않도록 분리
  .gitignore
  src/main/resources/application-dev.properties
  src/test/resources/application.properties
  src/test/resources/db/productDomainTableInit.sql
Labels: refactor

#31 ✨ Feat : Order 도메인 JWT적용
  src/main/java/com/hanbang/e/common/jwt/JwtUtil.java
  src/main/java/com/hanbang/e/member/service/MemberService.java
  src/main/java/com/hanbang/e/order/controller/OrderController.java
  src/test/java/com/hanbang/e/common/jwt/JwtUtilTest.java
  src/test/java/com/hanbang/e/member/util/JwtUtilTest.java
  src/test/java/com/hanbang/e/order/controller/OrderControllerTest.java
Labels: feature, refactor

#33 🧪 Test : 빌드 실패 이슈에 관한 테스트 코드 수정
  src/test/java/com/hanbang/e/order/controller/OrderControllerTest.java
  src/test/java/com/hanbang/e/product/controller/ProductControllerTest.java
Labels: bug, refactor, bugfix

#35 ✨ Feat: AOP API 실행 시간 측정
  src/main/java/com/hanbang/e/common/aop/TimeAop.java
Labels: feature

#38 🔨️ Refactor: 컨트롤러 테스트에서 Transational 처럼 동작하는 로직 작성
  src/test/java/com/hanbang/e/common/env/AcceptanceTestExecutionListener.java
  src/test/java/com/hanbang/e/product/controller/ProductControllerTest.java
  src/test/resources/application.properties
Labels: refactor

#40 🔨️ Refactor: 예외 메시지 관리용 enum 클래스 작성
  src/main/java/com/hanbang/e/common/exception/ExceptionMessage.java
Labels: feature

#45 🔨️ Refactor: Product 도메인 예외 메시지 enum으로 관리
  src/main/java/com/hanbang/e/common/exception/ExceptionMessage.java
  src/main/java/com/hanbang/e/product/service/ProductService.java
Labels: refactor

#50 🔨️ Refactor: 에러메세지 이넘으로 수정
  src/main/java/com/hanbang/e/common/exception/ExceptionMessage.java
  src/main/java/com/hanbang/e/member/service/MemberService.java
  src/main/java/com/hanbang/e/order/service/OrderService.java
Labels: refactor

#49 🔨️ Refactor: orderService 메소드 리턴값 수정
  src/main/java/com/hanbang/e/order/controller/OrderController.java
  src/main/java/com/hanbang/e/order/service/OrderService.java
  src/test/java/com/hanbang/e/order/service/OrderServiceTest.java
Labels: refactor

#43 🔨️ Refactor: ProductServie 메소드 리턴값 수정
  src/main/java/com/hanbang/e/product/controller/ProductController.java
  src/main/java/com/hanbang/e/product/service/ProductService.java
  src/test/java/com/hanbang/e/product/service/ProductServiceTest.java
Labels: refactor

#48 🔨️ Refactor : memberService 메소드 리턴값 수정
  src/main/java/com/hanbang/e/member/controller/MemberController.java
  src/main/java/com/hanbang/e/member/service/MemberService.java
  src/test/java/com/hanbang/e/member/service/MemberServiceTest.java
Labels: refactor

#57 🔥 Remove: 사용하지 않는 import문 제거
  src/main/java/com/hanbang/e/common/jwt/JwtUtil.java
  src/main/java/com/hanbang/e/member/controller/MemberController.java
  src/main/java/com/hanbang/e/member/service/MemberService.java
  src/main/java/com/hanbang/e/order/controller/OrderController.java
  src/main/java/com/hanbang/e/order/service/OrderService.java
  src/main/java/com/hanbang/e/product/entity/Product.java
  src/main/java/com/hanbang/e/product/service/ProductService.java
  src/test/java/com/hanbang/e/member/service/MemberServiceTest.java
  src/test/java/com/hanbang/e/order/controller/OrderControllerTest.java
  src/test/java/com/hanbang/e/order/repository/OrderRepositoryTest.java
  src/test/java/com/hanbang/e/product/controller/ProductControllerTest.java
Labels: enhancement

#58 ✨ Feat : CI 스크립트 작성
  .github/workflows/ci-pipeline.yml
  .github/workflows/gradle.yml
  .gitignore
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
Labels: feature

#59 ✨ Feat : CD 스크립트 작성
  .github/workflows/cd-pipeline.yml
  Dockerfile
  docker-compose.yml
Labels: feature

#68 ✨ Feat : Redisson 분산락 annotation 기반으로 사용하기 기능 추가
  src/main/java/com/hanbang/e/common/annotation/distributeLock/AopForTransaction.java
  src/main/java/com/hanbang/e/common/annotation/distributeLock/CustomSpringELParser.java
  src/main/java/com/hanbang/e/common/annotation/distributeLock/DistributeLock.java
  src/main/java/com/hanbang/e/common/annotation/distributeLock/DistributeLockAop.java
  src/main/java/com/hanbang/e/common/annotation/distributeLock/RedissonConfig.java
  src/main/java/com/hanbang/e/order/service/OrderService.java
  src/test/java/com/hanbang/e/order/service/OrderServiceDecreaseLockTest.java
  src/test/resources/application.properties
Labels: feature

#66 ✨ Feat : Redis, docker-compose 연결 작업
  docker-compose.yml
Labels: feature

#67 🔨️ Refactor : 상품 검색 API Querydsl 적용
  build.gradle
  src/main/java/com/hanbang/e/product/controller/ProductController.java
  src/main/java/com/hanbang/e/product/dto/ProductListResp.java
  src/main/java/com/hanbang/e/product/dto/ProductSimpleResp.java
  src/main/java/com/hanbang/e/product/repository/ProductRepository.java
  src/main/java/com/hanbang/e/product/repository/ProductRepositoryCustom.java
  src/main/java/com/hanbang/e/product/repository/ProductRepositoryImpl.java
  src/main/java/com/hanbang/e/product/service/ProductService.java
  src/test/java/com/hanbang/e/product/controller/ProductControllerTest.java
  src/test/java/com/hanbang/e/product/repository/ProductRepositoryTest.java
  src/test/java/com/hanbang/e/product/service/ProductServiceTest.java
Labels: refactor

#63 ✨ Feat : 주문생성/삭제 동시성 제어
  .github/workflows/ci-pipeline.yml
  build.gradle
  docker-compose.redis.yml
  src/main/java/com/hanbang/e/common/annotation/distributeLock/AopForTransaction.java
  src/main/java/com/hanbang/e/common/annotation/distributeLock/CustomSpringELParser.java
  src/main/java/com/hanbang/e/common/annotation/distributeLock/DistributeLock.java
  src/main/java/com/hanbang/e/common/annotation/distributeLock/DistributeLockAop.java
  src/main/java/com/hanbang/e/common/annotation/distributeLock/RedissonConfig.java
  src/main/java/com/hanbang/e/member/service/MemberService.java
  src/main/java/com/hanbang/e/order/controller/OrderController.java
  src/main/java/com/hanbang/e/order/service/OrderService.java
  src/main/resources/application.properties
  src/test/java/com/hanbang/e/member/service/memberServiceDecreaseLockTest.java
  src/test/java/com/hanbang/e/order/service/OrderServiceDecreaseLockTest.java
  src/test/resources/application.properties
Labels: feature

#73 🐛 Fix: docker spring 컨테이너, redis 컨테이너 사이 통신 연결
  .github/workflows/cd-pipeline.yml
  .github/workflows/ci-pipeline.yml
  .gitignore
  Dockerfile
  docker-compose.yml
  src/main/resources/application.properties
Labels: bugfix

#71 ✨ Feat : 상품 상세조회 기능 캐시 도입
  src/main/java/com/hanbang/e/common/config/RedisCacheConfig.java
  src/main/java/com/hanbang/e/common/config/RedissonConfig.java
  src/main/java/com/hanbang/e/product/controller/ProductController.java
  src/main/java/com/hanbang/e/product/dto/ProductDetailResp.java
  src/main/java/com/hanbang/e/product/service/ProductService.java
  src/test/java/com/hanbang/e/product/service/ProductServiceTest.java
Labels: feature

#78 ✨ Feat: Covering Index 사용하는 검색 API 작성
  src/main/java/com/hanbang/e/common/dto/PageResponseDto.java
  src/main/java/com/hanbang/e/product/controller/ProductController.java
  src/main/java/com/hanbang/e/product/entity/ProductCoveringIndex.java
  src/main/java/com/hanbang/e/product/repository/ProductCoveringIndexRepository.java
  src/main/java/com/hanbang/e/product/service/ProductService.java
  src/test/java/com/hanbang/e/product/repository/ProductCoveringIndexRepositoryTest.java
Labels: feature

#80 ✨ Feat : 동시성 제어시 Lock을 Annotation 로직 변경
  src/main/java/com/hanbang/e/common/annotation/distributeLock/DistributeLock.java
  src/main/java/com/hanbang/e/common/annotation/distributeLock/DistributeLockAop.java
  src/main/java/com/hanbang/e/common/exception/GlobalExceptionHandler.java
  src/main/java/com/hanbang/e/member/entity/Member.java
  src/main/java/com/hanbang/e/member/service/MemberService.java
  src/main/java/com/hanbang/e/order/service/OrderService.java
  src/test/java/com/hanbang/e/member/controller/MemberControllerTest.java
  src/test/java/com/hanbang/e/member/repository/MemberRepositoryTest.java
  src/test/java/com/hanbang/e/order/controller/OrderControllerTest.java
  src/test/java/com/hanbang/e/order/service/OrderServiceDecreaseLockTest.java
Labels: feature, refactor
